config/routes.rb
Rails.application.routes.draw do
  root 'homes#top'
  devise_for :users
  resources :albums, only: [:index, :show] do
    resources :reviews, only: [:index, :create]
  end
end

app/models/album.rb
class Album < ApplicationRecord
 attachment :image
 has_many :reviews, dependent: :destroy
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/image.rb
class Image < ApplicationRecord
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :user
  belongs_to :album
  validates :score, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :reviews, dependent: :destroy
end

app/controllers/albums_controller.rb
class AlbumsController < ApplicationController
  def index
    @albums = Album.all
  end

  def show
    @album = Album.find(params[:id])
    @review = Review.new
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected
  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:username])
  end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def top
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  def index
    @album = Album.find(params[:album_id])
    @reviews = @album.reviews
  end

  def create
    @review = Review.new(review_params)
    @review.user_id = current_user.id
    if @review.save
      redirect_to album_reviews_path(@review.album)
    else
      @album = Album.find(params[:id])
      render "albums/show"
    end
  end

  private
  def review_params
    params.require(:review).permit(:album_id, :score, :content)
  end
end

app/helpers/albums_helper.rb
module AlbumsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/views/albums/index.html.erb
<section class="section mt-6">
  <div class="container">
    <div class="columns is-centered">
      <div class="column is-5">
        <% @albums.each do |album| %>
          <div class="card mb-6">
            <header class="card-header">
              <p class="card-header-title">
                <%= album.name %>
              </p>
            </header>
            <div class="card-content">
              <div class="content">
                <div class="content average-score">
                  <div class="star-rating mb-2">
                    <div class="star-rating-front" style="width: %">★★★★★</div>
                    <div class="star-rating-back">★★★★★</div>
                  </div>
                  <div class="average-score-display ml-3 pt-2">
                  </div>
                </div>
              </div>
            </div>
            <footer class="card-footer">
              <%= link_to album_path(album), class:"button card-footer-item" do %>
                レビューを書く
              <% end %>
              <%= link_to album_reviews_path(album), class:"button card-footer-item" do %>
                レビューを見る
              <% end %>
            </footer>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</section>

app/views/albums/show.html.erb
<h1>Albums#show</h1>
<p>Find me in app/views/albums/show.html.erb</p>

app/views/homes/top.html.erb
  <div class="container">
    <div class="columns is-centered">
      <div class="column is-10">
          <div>
            <p class="is-size-4 has-text-weight-bold has-text-left">ASIAN</p>
            <p class="is-size-4 has-text-weight-bold has-text-left">KUNG-FU</p>
            <p class="is-size-4 has-text-weight-bold has-text-left">GENERATION</p>
          </div>
          <div  class="img">
            <%= image_tag 'AKG-image.png', size: '300x300' %>
          </div>
          <br>
          <div class="columns is-centered">
            <div class="column is-3">
              <%= link_to "ログイン", new_user_session_path, class: "button is-fullwidth" %>
              <br>
              <%= link_to "新規登録", new_user_registration_path, class: "button is-fullwidth" %>
            </div>
          </div>
      </div>
    </div>
  </div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>AkgReview</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <script src="https://kit.fontawesome.com/ac5873e769.js" crossorigin="anonymous"></script>
  </head>

  <body>
     <% if flash[:notice] %>
      <div class="notification is-info">
        <p class="notice"><%= notice %></p>
      </div>
    <% end %>
    <% if flash[:alert] %>
      <div class="notification is-danger">
        <p class="alert"><%= alert %></p>
      </div>
    <% end %>
    <nav class="navbar" role="navigation" aria-label="main navigation">
      <div class="navbar-brand">
        <p class="navbar-item">
          <%= link_to root_path do %>
            <strong class="is-size-8" style="font-family: sans-serif; color: black;"><i class="fas fa-dove fa-border"></i>AKFG-review</strong>
          <% end %>
        </p>
        <a role="button" class="navbar-burger burger" aria-label="menu" aria-expanded="false" data-target="navbarBasicExample">
          <span aria-hidden="true"></span>
          <span aria-hidden="true"></span>
          <span aria-hidden="true"></span>
        </a>
      </div>
      <div id="navbarBasicExample" class="navbar-menu">
        <div class="navbar-start">
          <%= link_to albums_path, class: "navbar-item" do %>
            アルバム一覧
          <% end %>
        </div>
        <div class="navbar-end">
          <div class="navbar-item">
            <% if user_signed_in? %>
              <p class="navbar-item">ようこそ <%= current_user.username %> さん</p>
            <% end %>
            <div class="buttons">
              <% if user_signed_in? %>
                <%= link_to destroy_user_session_path, method: :delete, class: "button" do %>
                  ログアウト
                <% end %>
              <% else %>
                <%= link_to new_user_session_path, class: "button" do %>
                  ログイン
                <% end %>
                <%= link_to new_user_registration_path, class: "button" do %>
                  新規登録
                <% end %>
              <% end %>
            </div>
          </div>
        </div>
      </div>
    </nav>
    <%= yield %>
  </body>
</html>

app/views/reviews/_form.html.erb
<p class="is-size-4 mb-3">レビューを書く</p>

<% if review.errors.any? %>
  <div class="notification is-danger">
    <h2><%= review.errors.count %>件のエラーがあります。</h2>
    <ul>
      <% review.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

<div class="rating-box mt-3">
  <%= form_with model: review , url: album_reviews_path(album), local: true do |f| %>
    <div class="main-rating">
      <div class="ratings mb-3">
        <span class="fa fa-star-o" id="star"></span>
        <span class="fa fa-star-o" id="star"></span>
        <span class="fa fa-star-o" id="star"></span>
        <span class="fa fa-star-o" id="star"></span>
        <span class="fa fa-star-o" id="star"></span>
      </div>
      <div class="ml-3 rating-value-display"><span id="rating-value-display">0</span>/5
      </div>
    </div>
    <%= f.hidden_field :album_id, value: album.id %>
    <%= f.hidden_field :score, id:"rating-value" %>
    <%= f.text_field :content, class: "textarea" %>
    <%= f.submit "保存", class: "button mt-3" %>
    <%= link_to "他のレビューを見る", album_reviews_path(album), class: "button light ml-3 mt-3" %>
  <% end %>
</div>

<%= javascript_include_tag "reviews.js" %>

app/views/reviews/index.html.erb
<section class="section mt-6">
  <div class="container">
    <div class="columns is-centered">
      <div class="column is-5">
        <div class="card mb-6">
          <header class="card-header">
            <p class="card-header-title">
              <%= @album.name %>
            </p>
          </header>
          <div class="card-content">
            <div class="content average-score">
              <div class="star-rating mb-2">
                <div class="star-rating-front" style="width:%">★★★★★</div>
                <div class="star-rating-back">★★★★★</div>
              </div>
              <div class="average-score-display ml-3 pt-2">
               点（<%= @album.reviews.count %>件のレビュー）
              </div>
            </div>
          </div>
        </div>
        <table class="table is-fullwidth has-text-centered">
          <thead>
            <tr>
              <th>ユーザー</th><th>点数</th><th>内容</th>
            </tr>
          </thead>
          <tbody>
            <% @reviews.each do |review| %>
              <tr>
                <td><%= review.user.username %></td>
                <td><%= review.score %></td>
                <td><%= review.content %></td>
              </tr>
            <% end %>
          </tbody>
        </table>
      </div>
    </div>
  </div>
</section>